name: Remote cache experiment

on:
  workflow_dispatch:
  push:

jobs:
  remote-cache-prime:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '17'
        - uses: gradle/actions/setup-gradle@v3
          with:
            cache-disabled: true
        - name: Run build to populate remote cache
          run: |
            ./gradlew --no-daemon --no-configuration-cache -Ddevelocity.deprecation.muteWarnings=true :app:assembleProdDebug
          env:
            DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

  remote-cache-experiment:
    needs: remote-cache-prime
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cache: ['transforms', 'kotlin-dsl', 'groovy-dsl']
        buildCache: ['build-cache', 'no-build-cache']
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - uses: gradle/actions/setup-gradle@v3
      with:
        cache-read-only: false
    - name: Run remote cache experiment
      run: |
        cache='${{ matrix.cache }}'
        buildCache='${{ matrix.buildCache }}'

        echo "Test caches/*/$cache removal with --$buildCache"

        echo "Running build once to fully populate Gradle User Home"
        ./gradlew -Dscan.tag.remote-cache-experiment-init --no-daemon --no-configuration-cache -Ddevelocity.deprecation.muteWarnings=true :app:assembleProdDebug
        killall -9 java
        mkdir cache1${{ matrix.cache }}-${{ matrix.buildCache }}
        cp -r ~/.gradle/caches/transforms-4/05ad1b9dc8cdc58ec95a4922378c6237/* cache1${{ matrix.cache }}-${{ matrix.buildCache }}/


        echo "Removing $cache from $homeDir/caches"
        rm -rf ~/.gradle/caches/*/$cache
        rm -rf ~/.gradle/caches/$cache-* # Also remove the transforms for Gradle 8.7

        # Always remove the local build cache since we are testing connection with remote build cache
        rm -rf ~/.gradle/caches/build-cache-1

        echo "Running build again with --${buildCache}"
        ./gradlew --$buildCache -Dscan.tag.remote-cache-experiment-$cache-$buildCache --no-configuration-cache -Ddevelocity.deprecation.muteWarnings=true -Dscan.uploadInBackground=false :app:assembleProdDebug
        mkdir cache2${{ matrix.cache }}-${{ matrix.buildCache }}
        cp -r ~/.gradle/caches/transforms-4/05ad1b9dc8cdc58ec95a4922378c6237/* cache2${{ matrix.cache }}-${{ matrix.buildCache }}/
      env:
        DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
    - name: Upload test reports
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: |
          cache1${{ matrix.cache }}-${{ matrix.buildCache }}/*
          cache2${{ matrix.cache }}-${{ matrix.buildCache }}/*
        
